apiVersion: project.mongodbatlas.crossplane.io/v1alpha3
kind: ApiKey
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha3/apikey
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: key-name
    roleNames:
    - ORG_READ_ONLY
