apiVersion: mongodbatlas.crossplane.io/v1alpha3
kind: Auditing
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1alpha3/auditing
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    auditAuthorizationSuccess: false
    auditFilter: '{ ''atype'': ''authenticate'', ''param'': {   ''user'': ''auditAdmin'',   ''db'':
      ''admin'',   ''mechanism'': ''SCRAM-SHA-1'' }}'
    enabled: true
    projectId: <project-id>
