// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha3 "github.com/crossplane-contrib/provider-mongodbatlas/apis/mongodbatlas/v1alpha3"
	v1alpha3online "github.com/crossplane-contrib/provider-mongodbatlas/apis/online/v1alpha3"
	v1alpha3org "github.com/crossplane-contrib/provider-mongodbatlas/apis/org/v1alpha3"
	v1alpha3project "github.com/crossplane-contrib/provider-mongodbatlas/apis/project/v1alpha3"
	v1alpha1 "github.com/crossplane-contrib/provider-mongodbatlas/apis/v1alpha1"
	v1beta1 "github.com/crossplane-contrib/provider-mongodbatlas/apis/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha3.SchemeBuilder.AddToScheme,
		v1alpha3online.SchemeBuilder.AddToScheme,
		v1alpha3org.SchemeBuilder.AddToScheme,
		v1alpha3project.SchemeBuilder.AddToScheme,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
